### AUTOGENERATED by v1Factory ###
# GENERIC IMPORTS
from django.contrib.auth.models import User
from django.db import models

# CODE
class Tweet(models.Model):
  content = models.TextField()
  author = models.ForeignKey(User)
  created_on = models.DateTimeField(auto_now_add=True)
